# Generated by Django 4.1.2 on 2024-12-05 14:04

from django.db import migrations

def add_default_blogposts(apps, schema_editor):
    BlogPost = apps.get_model('blog', 'BlogPost')
    BlogPost.objects.bulk_create([
        BlogPost(
            title="Introduction to Django",
            content="Django is a high-level Python web framework that enables rapid development of secure and maintainable websites. In this post, we explore the basics of Django, including its features and how to get started.",
            author="Admin"
        ),
        BlogPost(
            title="CSS Tips for Beautiful UIs",
            content="Good CSS can transform the look and feel of your website. In this article, we share some essential tips for creating visually appealing and responsive user interfaces.",
            author="Jane Doe"
        ),
        BlogPost(
            title="Why Learn Python",
            content="Python is one of the most versatile programming languages. Whether you're interested in web development, data science, or artificial intelligence, Python has something to offer.",
            author="John Smith"
        ),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(add_default_blogposts),
    ]
